<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.3</version>
        <relativePath/>
    </parent>

    <groupId>com.smartgrid</groupId>
    <artifactId>smartgrid</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>SmartGrid</name>
    <description>SmartGrid multi-module project</description>

    <properties>
        <java.version>17</java.version>
    </properties>

    <modules>
        <module>account-service</module>
        <module>node-manager</module>
        <module>measurement-service</module>
        <module>billing-service</module>
        <module>presentation-service</module>
        <module>analytics-service</module>
        <module>simulation-service</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.kafka</groupId>
                <artifactId>spring-kafka</artifactId>
                <version>3.3.3</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
